AllCops:
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

LineLength:
  Max: 100

MethodLength:
  Max: 15

Documentation:
  Enabled: false

RegexpLiteral:
  Exclude:
    - '**/*.gemspec'
    - '**/Guardfile'